global:
  scrape_interval: 15s     # Har 15 second mein /metrics hit karega

scrape_configs:
  - job_name: 'sentiment-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['sentiment-app:8000']   # Docker network mein container ka naam use hota hai, localhost nahi